#############################################################################
# Makefile for building: bin/MouseSense
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sun Mar 11 19:51:05 2012
# Project:  MouseSense.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile MouseSense.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQXT_GUI_LIB -DQXT_CORE_LIB -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -g0 -O3 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I/usr/include/QxtCore -I/usr/include/QxtGui -Iqtsingleapplication-2.6_1-opensource/src -I/usr/include -Ibuild/mocs -Ibuild/uis
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib -lQxtGui -lQxtCore -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/os/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/devicedialog.cpp \
		qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.cpp \
		qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.cpp build/mocs/moc_mainwindow.cpp \
		build/mocs/moc_devicedialog.cpp \
		build/mocs/moc_qtsingleapplication.cpp \
		build/mocs/moc_qtlocalpeer.cpp \
		build/rccs/qrc_resources.cpp
OBJECTS       = build/os/main.o \
		build/os/mainwindow.o \
		build/os/devicedialog.o \
		build/os/qtsingleapplication.o \
		build/os/qtlocalpeer.o \
		build/os/moc_mainwindow.o \
		build/os/moc_devicedialog.o \
		build/os/moc_qtsingleapplication.o \
		build/os/moc_qtlocalpeer.o \
		build/os/qrc_resources.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		qtsingleapplication-2.6_1-opensource/common.pri \
		qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.pri \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/qxtvars.prf \
		/usr/share/qt/mkspecs/features/qxt.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		MouseSense.pro
QMAKE_TARGET  = MouseSense
DESTDIR       = bin/
TARGET        = bin/MouseSense

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/uis/ui_mainwindow.h build/uis/ui_devicedialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MouseSense.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		qtsingleapplication-2.6_1-opensource/common.pri \
		qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.pri \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/qxtvars.prf \
		/usr/share/qt/mkspecs/features/qxt.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile MouseSense.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
qtsingleapplication-2.6_1-opensource/common.pri:
qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.pri:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/qxtvars.prf:
/usr/share/qt/mkspecs/features/qxt.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile MouseSense.pro

dist: 
	@$(CHK_DIR_EXISTS) build/os/MouseSense1.0.0 || $(MKDIR) build/os/MouseSense1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/os/MouseSense1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/devicedialog.h qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.h qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.h build/os/MouseSense1.0.0/ && $(COPY_FILE) --parents src/qrc/resources.qrc build/os/MouseSense1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/devicedialog.cpp qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.cpp qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.cpp build/os/MouseSense1.0.0/ && $(COPY_FILE) --parents src/forms/mainwindow.ui src/forms/devicedialog.ui build/os/MouseSense1.0.0/ && (cd `dirname build/os/MouseSense1.0.0` && $(TAR) MouseSense1.0.0.tar MouseSense1.0.0 && $(COMPRESS) MouseSense1.0.0.tar) && $(MOVE) `dirname build/os/MouseSense1.0.0`/MouseSense1.0.0.tar.gz . && $(DEL_FILE) -r build/os/MouseSense1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/mocs/moc_mainwindow.cpp build/mocs/moc_devicedialog.cpp build/mocs/moc_qtsingleapplication.cpp build/mocs/moc_qtlocalpeer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/mocs/moc_mainwindow.cpp build/mocs/moc_devicedialog.cpp build/mocs/moc_qtsingleapplication.cpp build/mocs/moc_qtlocalpeer.cpp
build/mocs/moc_mainwindow.cpp: build/uis/ui_mainwindow.h \
		/usr/include/QtCore/QVariant \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtGui/QAction \
		/usr/include/QtGui/qaction.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qicon.h \
		/usr/include/QtGui/qactiongroup.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		/usr/include/QtGui/QButtonGroup \
		/usr/include/QtGui/qbuttongroup.h \
		/usr/include/QtGui/QComboBox \
		/usr/include/QtGui/qcombobox.h \
		/usr/include/QtGui/qabstractitemdelegate.h \
		/usr/include/QtGui/qstyleoption.h \
		/usr/include/QtGui/qabstractspinbox.h \
		/usr/include/QtGui/qvalidator.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtGui/qslider.h \
		/usr/include/QtGui/qabstractslider.h \
		/usr/include/QtGui/qstyle.h \
		/usr/include/QtGui/qtabbar.h \
		/usr/include/QtGui/qtabwidget.h \
		/usr/include/QtGui/qrubberband.h \
		/usr/include/QtGui/qframe.h \
		/usr/include/QtCore/qabstractitemmodel.h \
		/usr/include/QtGui/QHBoxLayout \
		/usr/include/QtGui/qboxlayout.h \
		/usr/include/QtGui/qlayout.h \
		/usr/include/QtGui/qlayoutitem.h \
		/usr/include/QtGui/qgridlayout.h \
		/usr/include/QtGui/QHeaderView \
		/usr/include/QtGui/qheaderview.h \
		/usr/include/QtGui/qabstractitemview.h \
		/usr/include/QtGui/qabstractscrollarea.h \
		/usr/include/QtGui/qitemselectionmodel.h \
		/usr/include/QtGui/QLabel \
		/usr/include/QtGui/qlabel.h \
		/usr/include/QtGui/QMainWindow \
		/usr/include/QtGui/qmainwindow.h \
		/usr/include/QtGui/QMenu \
		/usr/include/QtGui/qmenu.h \
		/usr/include/QtGui/QMenuBar \
		/usr/include/QtGui/qmenubar.h \
		/usr/include/QtGui/QPushButton \
		/usr/include/QtGui/qpushbutton.h \
		/usr/include/QtGui/qabstractbutton.h \
		/usr/include/QtGui/QSpacerItem \
		/usr/include/QtGui/QSpinBox \
		/usr/include/QtGui/qspinbox.h \
		/usr/include/QtGui/QVBoxLayout \
		/usr/include/QtGui/QWidget \
		src/devicedialog.h \
		build/uis/ui_devicedialog.h \
		/usr/include/QtGui/QDialog \
		/usr/include/QtGui/qdialog.h \
		/usr/include/QtGui/QGridLayout \
		/usr/include/QtGui/QLineEdit \
		/usr/include/QtGui/qlineedit.h \
		/usr/include/QtGui/qtextcursor.h \
		/usr/include/QtGui/qtextformat.h \
		/usr/include/QtGui/qpen.h \
		/usr/include/QtGui/qtextoption.h \
		src/mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o build/mocs/moc_mainwindow.cpp

build/mocs/moc_devicedialog.cpp: build/uis/ui_devicedialog.h \
		/usr/include/QtCore/QVariant \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtGui/QAction \
		/usr/include/QtGui/qaction.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qicon.h \
		/usr/include/QtGui/qactiongroup.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		/usr/include/QtGui/QButtonGroup \
		/usr/include/QtGui/qbuttongroup.h \
		/usr/include/QtGui/QDialog \
		/usr/include/QtGui/qdialog.h \
		/usr/include/QtGui/QGridLayout \
		/usr/include/QtGui/qgridlayout.h \
		/usr/include/QtGui/qlayout.h \
		/usr/include/QtGui/qlayoutitem.h \
		/usr/include/QtGui/qboxlayout.h \
		/usr/include/QtGui/QHBoxLayout \
		/usr/include/QtGui/QHeaderView \
		/usr/include/QtGui/qheaderview.h \
		/usr/include/QtGui/qabstractitemview.h \
		/usr/include/QtGui/qabstractscrollarea.h \
		/usr/include/QtGui/qframe.h \
		/usr/include/QtCore/qabstractitemmodel.h \
		/usr/include/QtGui/qitemselectionmodel.h \
		/usr/include/QtGui/qabstractitemdelegate.h \
		/usr/include/QtGui/qstyleoption.h \
		/usr/include/QtGui/qabstractspinbox.h \
		/usr/include/QtGui/qvalidator.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtGui/qslider.h \
		/usr/include/QtGui/qabstractslider.h \
		/usr/include/QtGui/qstyle.h \
		/usr/include/QtGui/qtabbar.h \
		/usr/include/QtGui/qtabwidget.h \
		/usr/include/QtGui/qrubberband.h \
		/usr/include/QtGui/QLabel \
		/usr/include/QtGui/qlabel.h \
		/usr/include/QtGui/QLineEdit \
		/usr/include/QtGui/qlineedit.h \
		/usr/include/QtGui/qtextcursor.h \
		/usr/include/QtGui/qtextformat.h \
		/usr/include/QtGui/qpen.h \
		/usr/include/QtGui/qtextoption.h \
		/usr/include/QtGui/QPushButton \
		/usr/include/QtGui/qpushbutton.h \
		/usr/include/QtGui/qabstractbutton.h \
		/usr/include/QtGui/QSpacerItem \
		/usr/include/QtGui/QVBoxLayout \
		src/devicedialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/devicedialog.h -o build/mocs/moc_devicedialog.cpp

build/mocs/moc_qtsingleapplication.cpp: /usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.h -o build/mocs/moc_qtsingleapplication.cpp

build/mocs/moc_qtlocalpeer.cpp: /usr/include/QtNetwork/QLocalServer \
		/usr/include/QtNetwork/qlocalserver.h \
		/usr/include/QtNetwork/qabstractsocket.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qdebug.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qtextstream.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qtextcodec.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtCore/QPoint \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qcontiguouscache.h \
		/usr/include/QtNetwork/QLocalSocket \
		/usr/include/QtNetwork/qlocalsocket.h \
		/usr/include/QtCore/QDir \
		/usr/include/QtCore/qdir.h \
		/usr/include/QtCore/qfileinfo.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile.h \
		/usr/include/QtCore/QFile \
		/usr/include/QtCore/QVector \
		qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.h -o build/mocs/moc_qtlocalpeer.cpp

compiler_rcc_make_all: build/rccs/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rccs/qrc_resources.cpp
build/rccs/qrc_resources.cpp: src/qrc/resources.qrc \
		src/qrc/images/mouseTray.png \
		src/qrc/images/mouseTray6.png
	/usr/bin/rcc -name resources src/qrc/resources.qrc -o build/rccs/qrc_resources.cpp

compiler_image_collection_make_all: build/uis/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/uis/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/uis/ui_mainwindow.h build/uis/ui_devicedialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/uis/ui_mainwindow.h build/uis/ui_devicedialog.h
build/uis/ui_mainwindow.h: src/forms/mainwindow.ui
	/usr/bin/uic src/forms/mainwindow.ui -o build/uis/ui_mainwindow.h

build/uis/ui_devicedialog.h: src/forms/devicedialog.ui
	/usr/bin/uic src/forms/devicedialog.ui -o build/uis/ui_devicedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/os/main.o: src/main.cpp qtsingleapplication-2.6_1-opensource/src/QtSingleApplication \
		qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		src/mainwindow.h \
		build/uis/ui_mainwindow.h \
		/usr/include/QtCore/QVariant \
		/usr/include/QtGui/QAction \
		/usr/include/QtGui/qaction.h \
		/usr/include/QtGui/qicon.h \
		/usr/include/QtGui/qactiongroup.h \
		/usr/include/QtGui/QButtonGroup \
		/usr/include/QtGui/qbuttongroup.h \
		/usr/include/QtGui/QComboBox \
		/usr/include/QtGui/qcombobox.h \
		/usr/include/QtGui/qabstractitemdelegate.h \
		/usr/include/QtGui/qstyleoption.h \
		/usr/include/QtGui/qabstractspinbox.h \
		/usr/include/QtGui/qvalidator.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtGui/qslider.h \
		/usr/include/QtGui/qabstractslider.h \
		/usr/include/QtGui/qstyle.h \
		/usr/include/QtGui/qtabbar.h \
		/usr/include/QtGui/qtabwidget.h \
		/usr/include/QtGui/qrubberband.h \
		/usr/include/QtGui/qframe.h \
		/usr/include/QtCore/qabstractitemmodel.h \
		/usr/include/QtGui/QHBoxLayout \
		/usr/include/QtGui/qboxlayout.h \
		/usr/include/QtGui/qlayout.h \
		/usr/include/QtGui/qlayoutitem.h \
		/usr/include/QtGui/qgridlayout.h \
		/usr/include/QtGui/QHeaderView \
		/usr/include/QtGui/qheaderview.h \
		/usr/include/QtGui/qabstractitemview.h \
		/usr/include/QtGui/qabstractscrollarea.h \
		/usr/include/QtGui/qitemselectionmodel.h \
		/usr/include/QtGui/QLabel \
		/usr/include/QtGui/qlabel.h \
		/usr/include/QtGui/QMainWindow \
		/usr/include/QtGui/qmainwindow.h \
		/usr/include/QtGui/QMenu \
		/usr/include/QtGui/qmenu.h \
		/usr/include/QtGui/QMenuBar \
		/usr/include/QtGui/qmenubar.h \
		/usr/include/QtGui/QPushButton \
		/usr/include/QtGui/qpushbutton.h \
		/usr/include/QtGui/qabstractbutton.h \
		/usr/include/QtGui/QSpacerItem \
		/usr/include/QtGui/QSpinBox \
		/usr/include/QtGui/qspinbox.h \
		/usr/include/QtGui/QVBoxLayout \
		/usr/include/QtGui/QWidget \
		src/devicedialog.h \
		build/uis/ui_devicedialog.h \
		/usr/include/QtGui/QDialog \
		/usr/include/QtGui/qdialog.h \
		/usr/include/QtGui/QGridLayout \
		/usr/include/QtGui/QLineEdit \
		/usr/include/QtGui/qlineedit.h \
		/usr/include/QtGui/qtextcursor.h \
		/usr/include/QtGui/qtextformat.h \
		/usr/include/QtGui/qpen.h \
		/usr/include/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/main.o src/main.cpp

build/os/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		build/uis/ui_mainwindow.h \
		/usr/include/QtCore/QVariant \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtGui/QAction \
		/usr/include/QtGui/qaction.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qicon.h \
		/usr/include/QtGui/qactiongroup.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		/usr/include/QtGui/QButtonGroup \
		/usr/include/QtGui/qbuttongroup.h \
		/usr/include/QtGui/QComboBox \
		/usr/include/QtGui/qcombobox.h \
		/usr/include/QtGui/qabstractitemdelegate.h \
		/usr/include/QtGui/qstyleoption.h \
		/usr/include/QtGui/qabstractspinbox.h \
		/usr/include/QtGui/qvalidator.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtGui/qslider.h \
		/usr/include/QtGui/qabstractslider.h \
		/usr/include/QtGui/qstyle.h \
		/usr/include/QtGui/qtabbar.h \
		/usr/include/QtGui/qtabwidget.h \
		/usr/include/QtGui/qrubberband.h \
		/usr/include/QtGui/qframe.h \
		/usr/include/QtCore/qabstractitemmodel.h \
		/usr/include/QtGui/QHBoxLayout \
		/usr/include/QtGui/qboxlayout.h \
		/usr/include/QtGui/qlayout.h \
		/usr/include/QtGui/qlayoutitem.h \
		/usr/include/QtGui/qgridlayout.h \
		/usr/include/QtGui/QHeaderView \
		/usr/include/QtGui/qheaderview.h \
		/usr/include/QtGui/qabstractitemview.h \
		/usr/include/QtGui/qabstractscrollarea.h \
		/usr/include/QtGui/qitemselectionmodel.h \
		/usr/include/QtGui/QLabel \
		/usr/include/QtGui/qlabel.h \
		/usr/include/QtGui/QMainWindow \
		/usr/include/QtGui/qmainwindow.h \
		/usr/include/QtGui/QMenu \
		/usr/include/QtGui/qmenu.h \
		/usr/include/QtGui/QMenuBar \
		/usr/include/QtGui/qmenubar.h \
		/usr/include/QtGui/QPushButton \
		/usr/include/QtGui/qpushbutton.h \
		/usr/include/QtGui/qabstractbutton.h \
		/usr/include/QtGui/QSpacerItem \
		/usr/include/QtGui/QSpinBox \
		/usr/include/QtGui/qspinbox.h \
		/usr/include/QtGui/QVBoxLayout \
		/usr/include/QtGui/QWidget \
		src/devicedialog.h \
		build/uis/ui_devicedialog.h \
		/usr/include/QtGui/QDialog \
		/usr/include/QtGui/qdialog.h \
		/usr/include/QtGui/QGridLayout \
		/usr/include/QtGui/QLineEdit \
		/usr/include/QtGui/qlineedit.h \
		/usr/include/QtGui/qtextcursor.h \
		/usr/include/QtGui/qtextformat.h \
		/usr/include/QtGui/qpen.h \
		/usr/include/QtGui/qtextoption.h \
		/usr/include/QxtGui/QxtGlobalShortcut \
		/usr/include/QxtGui/qxtglobalshortcut.h \
		/usr/include/QxtCore/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/mainwindow.o src/mainwindow.cpp

build/os/devicedialog.o: src/devicedialog.cpp src/devicedialog.h \
		build/uis/ui_devicedialog.h \
		/usr/include/QtCore/QVariant \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtGui/QAction \
		/usr/include/QtGui/qaction.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qicon.h \
		/usr/include/QtGui/qactiongroup.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		/usr/include/QtGui/QButtonGroup \
		/usr/include/QtGui/qbuttongroup.h \
		/usr/include/QtGui/QDialog \
		/usr/include/QtGui/qdialog.h \
		/usr/include/QtGui/QGridLayout \
		/usr/include/QtGui/qgridlayout.h \
		/usr/include/QtGui/qlayout.h \
		/usr/include/QtGui/qlayoutitem.h \
		/usr/include/QtGui/qboxlayout.h \
		/usr/include/QtGui/QHBoxLayout \
		/usr/include/QtGui/QHeaderView \
		/usr/include/QtGui/qheaderview.h \
		/usr/include/QtGui/qabstractitemview.h \
		/usr/include/QtGui/qabstractscrollarea.h \
		/usr/include/QtGui/qframe.h \
		/usr/include/QtCore/qabstractitemmodel.h \
		/usr/include/QtGui/qitemselectionmodel.h \
		/usr/include/QtGui/qabstractitemdelegate.h \
		/usr/include/QtGui/qstyleoption.h \
		/usr/include/QtGui/qabstractspinbox.h \
		/usr/include/QtGui/qvalidator.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtGui/qslider.h \
		/usr/include/QtGui/qabstractslider.h \
		/usr/include/QtGui/qstyle.h \
		/usr/include/QtGui/qtabbar.h \
		/usr/include/QtGui/qtabwidget.h \
		/usr/include/QtGui/qrubberband.h \
		/usr/include/QtGui/QLabel \
		/usr/include/QtGui/qlabel.h \
		/usr/include/QtGui/QLineEdit \
		/usr/include/QtGui/qlineedit.h \
		/usr/include/QtGui/qtextcursor.h \
		/usr/include/QtGui/qtextformat.h \
		/usr/include/QtGui/qpen.h \
		/usr/include/QtGui/qtextoption.h \
		/usr/include/QtGui/QPushButton \
		/usr/include/QtGui/qpushbutton.h \
		/usr/include/QtGui/qabstractbutton.h \
		/usr/include/QtGui/QSpacerItem \
		/usr/include/QtGui/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/devicedialog.o src/devicedialog.cpp

build/os/qtsingleapplication.o: qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.cpp qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.h \
		/usr/include/QtGui/QApplication \
		/usr/include/QtGui/qapplication.h \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		/usr/include/QtGui/qwindowdefs.h \
		/usr/include/QtGui/qmacdefines_mac.h \
		/usr/include/QtGui/qwindowdefs_win.h \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtCore/qsize.h \
		/usr/include/QtGui/qcursor.h \
		/usr/include/QtGui/qdesktopwidget.h \
		/usr/include/QtGui/qwidget.h \
		/usr/include/QtCore/qmargins.h \
		/usr/include/QtGui/qpaintdevice.h \
		/usr/include/QtCore/qrect.h \
		/usr/include/QtGui/qpalette.h \
		/usr/include/QtGui/qcolor.h \
		/usr/include/QtGui/qrgb.h \
		/usr/include/QtGui/qbrush.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/QPoint \
		/usr/include/QtGui/qmatrix.h \
		/usr/include/QtGui/qpolygon.h \
		/usr/include/QtGui/qregion.h \
		/usr/include/QtCore/qline.h \
		/usr/include/QtGui/qwmatrix.h \
		/usr/include/QtGui/qtransform.h \
		/usr/include/QtGui/qpainterpath.h \
		/usr/include/QtGui/qimage.h \
		/usr/include/QtGui/qpixmap.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtGui/qfont.h \
		/usr/include/QtGui/qfontmetrics.h \
		/usr/include/QtGui/qfontinfo.h \
		/usr/include/QtGui/qsizepolicy.h \
		/usr/include/QtGui/qkeysequence.h \
		/usr/include/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/QtGui/QPlatformWindow \
		/usr/include/QtGui/qplatformwindow_qpa.h \
		/usr/include/QtGui/qevent.h \
		/usr/include/QtGui/qmime.h \
		/usr/include/QtCore/qmimedata.h \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtGui/qdrag.h \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtGui/qtransportauth_qws.h \
		/usr/include/QtCore/qbuffer.h \
		/usr/include/QtCore/qpointer.h \
		qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.h \
		/usr/include/QtNetwork/QLocalServer \
		/usr/include/QtNetwork/qlocalserver.h \
		/usr/include/QtNetwork/qabstractsocket.h \
		/usr/include/QtCore/qdebug.h \
		/usr/include/QtCore/qtextstream.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtCore/qtextcodec.h \
		/usr/include/QtCore/qcontiguouscache.h \
		/usr/include/QtNetwork/QLocalSocket \
		/usr/include/QtNetwork/qlocalsocket.h \
		/usr/include/QtCore/QDir \
		/usr/include/QtCore/qdir.h \
		/usr/include/QtCore/qfileinfo.h \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile.h \
		/usr/include/QtCore/QFile \
		/usr/include/QtCore/QVector \
		/usr/include/QtGui/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/qtsingleapplication.o qtsingleapplication-2.6_1-opensource/src/qtsingleapplication.cpp

build/os/qtlocalpeer.o: qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.cpp qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.h \
		/usr/include/QtNetwork/QLocalServer \
		/usr/include/QtNetwork/qlocalserver.h \
		/usr/include/QtNetwork/qabstractsocket.h \
		/usr/include/QtCore/qiodevice.h \
		/usr/include/QtCore/qobject.h \
		/usr/include/QtCore/qobjectdefs.h \
		/usr/include/QtCore/qnamespace.h \
		/usr/include/QtCore/qglobal.h \
		/usr/include/QtCore/qconfig.h \
		/usr/include/QtCore/qfeatures.h \
		/usr/include/QtCore/qstring.h \
		/usr/include/QtCore/qchar.h \
		/usr/include/QtCore/qbytearray.h \
		/usr/include/QtCore/qatomic.h \
		/usr/include/QtCore/qbasicatomic.h \
		/usr/include/QtCore/qatomic_bootstrap.h \
		/usr/include/QtCore/qatomic_arch.h \
		/usr/include/QtCore/qatomic_integrity.h \
		/usr/include/QtCore/qatomic_vxworks.h \
		/usr/include/QtCore/qatomic_powerpc.h \
		/usr/include/QtCore/qatomic_alpha.h \
		/usr/include/QtCore/qatomic_arm.h \
		/usr/include/QtCore/qatomic_armv7.h \
		/usr/include/QtCore/qatomic_armv6.h \
		/usr/include/QtCore/qatomic_armv5.h \
		/usr/include/QtCore/qatomic_avr32.h \
		/usr/include/QtCore/qatomic_bfin.h \
		/usr/include/QtCore/qatomic_generic.h \
		/usr/include/QtCore/qatomic_i386.h \
		/usr/include/QtCore/qatomic_ia64.h \
		/usr/include/QtCore/qatomic_macosx.h \
		/usr/include/QtCore/qatomic_x86_64.h \
		/usr/include/QtCore/qatomic_mips.h \
		/usr/include/QtCore/qatomic_parisc.h \
		/usr/include/QtCore/qatomic_s390.h \
		/usr/include/QtCore/qatomic_sparc.h \
		/usr/include/QtCore/qatomic_windows.h \
		/usr/include/QtCore/qatomic_windowsce.h \
		/usr/include/QtCore/qatomic_symbian.h \
		/usr/include/QtCore/qatomic_sh.h \
		/usr/include/QtCore/qatomic_sh4a.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/xlocale.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/bits/string3.h \
		/usr/include/Qt3Support/q3cstring.h \
		/usr/include/QtCore/qstringbuilder.h \
		/usr/include/QtCore/qmap.h \
		/usr/include/QtCore/qiterator.h \
		/usr/include/QtCore/qlist.h \
		/usr/include/QtCore/qalgorithms.h \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/QtCore/qcoreevent.h \
		/usr/include/QtCore/qscopedpointer.h \
		/usr/include/QtCore/qdebug.h \
		/usr/include/QtCore/qhash.h \
		/usr/include/QtCore/qpair.h \
		/usr/include/QtCore/qdatastream.h \
		/usr/include/QtCore/qtextstream.h \
		/usr/include/QtCore/qlocale.h \
		/usr/include/QtCore/qvariant.h \
		/usr/include/QtCore/qmetatype.h \
		/usr/include/QtCore/qtextcodec.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/QtCore/qvector.h \
		/usr/include/QtCore/QPointF \
		/usr/include/QtCore/qpoint.h \
		/usr/include/QtCore/QPoint \
		/usr/include/QtCore/qset.h \
		/usr/include/QtCore/qcontiguouscache.h \
		/usr/include/QtNetwork/QLocalSocket \
		/usr/include/QtNetwork/qlocalsocket.h \
		/usr/include/QtCore/QDir \
		/usr/include/QtCore/qdir.h \
		/usr/include/QtCore/qfileinfo.h \
		/usr/include/QtCore/qfile.h \
		/usr/include/QtCore/qshareddata.h \
		/usr/include/QtCore/qstringlist.h \
		/usr/include/QtCore/qregexp.h \
		/usr/include/QtCore/qstringmatcher.h \
		/usr/include/Qt3Support/q3valuelist.h \
		/usr/include/QtCore/qlinkedlist.h \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile.h \
		/usr/include/QtCore/QFile \
		/usr/include/QtCore/QVector \
		/usr/include/QtCore/QCoreApplication \
		/usr/include/QtCore/qcoreapplication.h \
		/usr/include/QtCore/qeventloop.h \
		/usr/include/QtCore/QTime \
		/usr/include/QtCore/qdatetime.h \
		/usr/include/QtCore/qsharedpointer.h \
		/usr/include/QtCore/qsharedpointer_impl.h \
		/usr/include/QtCore/QLibrary \
		/usr/include/QtCore/qlibrary.h \
		/usr/include/QtCore/qt_windows.h \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile.cpp \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile_win.cpp \
		/usr/include/QtCore/QFileInfo \
		qtsingleapplication-2.6_1-opensource/src/qtlockedfile_unix.cpp \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/asm/errno.h \
		/usr/include/asm-generic/errno.h \
		/usr/include/asm-generic/errno-base.h \
		/usr/include/unistd.h \
		/usr/include/bits/posix_opt.h \
		/usr/include/bits/environments.h \
		/usr/include/bits/confname.h \
		/usr/include/bits/unistd.h \
		/usr/include/fcntl.h \
		/usr/include/bits/fcntl.h \
		/usr/include/bits/uio.h \
		/usr/include/bits/stat.h \
		/usr/include/bits/fcntl2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/qtlocalpeer.o qtsingleapplication-2.6_1-opensource/src/qtlocalpeer.cpp

build/os/moc_mainwindow.o: build/mocs/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/moc_mainwindow.o build/mocs/moc_mainwindow.cpp

build/os/moc_devicedialog.o: build/mocs/moc_devicedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/moc_devicedialog.o build/mocs/moc_devicedialog.cpp

build/os/moc_qtsingleapplication.o: build/mocs/moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/moc_qtsingleapplication.o build/mocs/moc_qtsingleapplication.cpp

build/os/moc_qtlocalpeer.o: build/mocs/moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/moc_qtlocalpeer.o build/mocs/moc_qtlocalpeer.cpp

build/os/qrc_resources.o: build/rccs/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/os/qrc_resources.o build/rccs/qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

